export const interviewQuestions = {
  /* -------------------------------------------------------------------------- */
  /* 🧠 HR & Behavioral Questions (30)                                          */
  /* -------------------------------------------------------------------------- */
  hr: [
    "Walk me through your background and experience.",
    "Why are you interested in working for our company?",
    "What do you consider your greatest professional strength?",
    "Tell me about a time you faced a significant challenge at work and how you handled it.",
    "Where do you see yourself in 5 years?",
    "Describe a situation where you had to work with a difficult team member.",
    "How do you handle tight deadlines and pressure?",
    "What motivates you to do your best work?",
    "Why should we hire you over other candidates?",
    "Tell me about a time you failed and what you learned from it.",
    "What type of work environment do you thrive in?",
    "How do you prioritize tasks when managing multiple projects?",
    "Describe your ideal manager or leadership style.",
    "Tell me about a time you went above and beyond for your team.",
    "What are your career goals for the next few years?",
    "How do you handle feedback or criticism?",
    "What’s your biggest professional achievement so far?",
    "Describe a situation where you took initiative without being asked.",
    "How do you balance work-life commitments?",
    "Tell me about a time you had to make a tough decision at work.",
    "What are your strategies for dealing with stress?",
    "What kind of company culture do you value most?",
    "How do you adapt to changes in the workplace?",
    "Tell me about a time you resolved a conflict within a team.",
    "What motivates you to keep learning and growing?",
    "How do you stay productive when working remotely?",
    "What’s something you’ve learned from a past mistake?",
    "How do you ensure effective communication in a team?",
    "Describe a situation where you had to meet an unrealistic deadline.",
    "What makes you passionate about your field?"
  ],

  /* -------------------------------------------------------------------------- */
  /* ⚙️ Technical Interviews by Domain (30 each)                               */
  /* -------------------------------------------------------------------------- */
  technical: {
    programming: [
      "Explain the principles of object-oriented programming.",
      "What’s the difference between compilation and interpretation?",
      "How do you manage memory in programming languages?",
      "Explain polymorphism with a practical example.",
      "What are design patterns and why are they important?",
      "Explain the concept of recursion and give an example.",
      "What’s the difference between stack and heap memory?",
      "What are data types and why are they important?",
      "What is exception handling and how does it work?",
      "Explain the difference between pass by value and pass by reference.",
      "What’s a constructor in object-oriented programming?",
      "How do garbage collectors work in managed languages?",
      "What’s the difference between an interface and an abstract class?",
      "Explain multithreading and its challenges.",
      "What is synchronization and why is it needed?",
      "What are lambda expressions used for?",
      "Explain functional vs. imperative programming.",
      "What’s the difference between procedural and object-oriented programming?",
      "Describe a linked list and its advantages.",
      "Explain big O notation and why it matters.",
      "What are generics in programming?",
      "Explain the difference between compile-time and run-time errors.",
      "What are software design principles like SOLID?",
      "What is the difference between deep copy and shallow copy?",
      "Explain how version control systems work (like Git).",
      "Describe a time you optimized code performance.",
      "What is dependency injection?",
      "Explain how you would debug a segmentation fault.",
      "How do you handle concurrent programming issues?",
      "What is the difference between APIs and libraries?"
    ],

    webdev: [
      "Explain how the browser renders a web page.",
      "What are the differences between HTTP/1.1 and HTTP/2?",
      "How does React's virtual DOM improve performance?",
      "Explain CORS and why it's important for web security.",
      "What are service workers and how do they enable PWAs?",
      "Explain how cookies, localStorage, and sessionStorage differ.",
      "What’s the difference between client-side and server-side rendering?",
      "What are REST APIs and how do they work?",
      "How does the fetch API differ from XMLHttpRequest?",
      "Explain lazy loading and why it’s used.",
      "What’s the purpose of WebSockets?",
      "Explain the box model in CSS.",
      "What is the difference between inline, inline-block, and block elements?",
      "What are CSS preprocessors and why use them?",
      "Explain how flexbox and grid differ.",
      "What are semantic HTML tags and why are they important?",
      "Explain how to make a website responsive.",
      "What are Single Page Applications (SPA)?",
      "What’s a CDN and why use it?",
      "Explain web accessibility standards (WCAG).",
      "What are CSS animations and transitions?",
      "How do you optimize website performance?",
      "What’s cross-site scripting (XSS) and how to prevent it?",
      "Explain the role of DNS in web loading.",
      "What’s difference between PUT, PATCH, and POST methods?",
      "How does browser caching improve speed?",
      "What is a Content Security Policy?",
      "Explain the concept of hydration in SSR frameworks.",
      "What’s a micro frontend architecture?",
      "How do you handle SEO in SPAs?"
    ],

    datascience: [
      "Explain the bias-variance tradeoff in machine learning.",
      "How would you handle missing data in a dataset?",
      "What's the difference between supervised and unsupervised learning?",
      "Explain cross-validation and why it's important.",
      "How do you evaluate the performance of a classification model?",
      "Explain the concept of feature scaling.",
      "What is dimensionality reduction?",
      "How do you deal with imbalanced datasets?",
      "What’s the difference between PCA and LDA?",
      "Explain regularization and why it’s used.",
      "What is the curse of dimensionality?",
      "How do you detect outliers in data?",
      "Explain overfitting and underfitting.",
      "What’s the difference between precision and recall?",
      "Explain F1-score and when to use it.",
      "How do you perform feature selection?",
      "What’s the difference between bagging and boosting?",
      "Explain ensemble learning.",
      "What is gradient descent?",
      "What’s a confusion matrix?",
      "How do you visualize correlations in a dataset?",
      "What’s a ROC curve?",
      "Explain k-means clustering.",
      "What’s the difference between regression and classification?",
      "What are decision trees and how do they work?",
      "Explain random forests.",
      "What are support vector machines?",
      "How do neural networks differ from traditional ML models?",
      "What are the assumptions of linear regression?",
      "How would you explain your ML model to a non-technical audience?"
    ],

    'ai-ml': [
      "What is the difference between AI, machine learning, and deep learning?",
      "Explain how a neural network learns through backpropagation.",
      "What are some common activation functions and when would you use them?",
      "How does a convolutional neural network work for image processing?",
      "Explain the concept of overfitting and how to prevent it.",
      "What is gradient descent and how does it work?",
      "Explain different types of neural network architectures.",
      "What is transfer learning?",
      "What are hyperparameters in ML models?",
      "How do RNNs differ from CNNs?",
      "What is attention mechanism in transformers?",
      "Explain the architecture of GPT or BERT.",
      "What is reinforcement learning?",
      "What is Q-learning?",
      "What’s the difference between online and batch learning?",
      "How do you evaluate an ML model’s generalization?",
      "Explain dropout and batch normalization.",
      "What is a confusion matrix?",
      "What are embeddings in ML?",
      "How do GANs work?",
      "What is data augmentation and why use it?",
      "Explain bias in AI models.",
      "What is model interpretability and explainable AI?",
      "How do you choose the right optimizer?",
      "What are autoencoders used for?",
      "Explain ROC-AUC in model evaluation.",
      "What’s the vanishing gradient problem?",
      "How do you deploy AI models to production?",
      "What is fine-tuning in pre-trained models?",
      "How do you ensure fairness and ethics in AI?"
    ],

    'system-design': [
      "How would you design a URL shortening service like TinyURL?",
      "Explain the CAP theorem and its implications for distributed systems.",
      "How would you design a social media news feed?",
      "What factors would you consider when designing a video streaming service?",
      "How do you approach database scaling for high-traffic applications?",
      "Design a chat application like WhatsApp.",
      "How would you design a ride-sharing service like Uber?",
      "Explain horizontal vs vertical scaling.",
      "What’s the role of load balancers?",
      "Design an email delivery system.",
      "What is caching and how would you implement it?",
      "Explain message queues and their importance.",
      "How would you design a real-time notification system?",
      "What’s the difference between SQL and NoSQL databases?",
      "How do you handle data partitioning?",
      "Design a file storage system like Google Drive.",
      "What is replication and how does it help reliability?",
      "How would you ensure fault tolerance?",
      "Design a payment gateway system.",
      "What’s the difference between monolithic and microservices architecture?",
      "Explain API gateway design.",
      "How do you manage authentication across distributed services?",
      "What’s the role of CDN in system design?",
      "How would you log and monitor services?",
      "Design a search engine backend.",
      "Explain event-driven architecture.",
      "How do you ensure high availability?",
      "How would you design a recommendation system?",
      "What is rate limiting and how to implement it?",
      "Explain data consistency models."
    ],

    dsa: [
      "Explain the time complexity of various sorting algorithms.",
      "How does a hash table work internally?",
      "What's the difference between BFS and DFS?",
      "Explain dynamic programming with an example.",
      "How would you find the shortest path in a weighted graph?",
      "What’s a binary search and when to use it?",
      "Explain the concept of recursion.",
      "What’s the difference between stack and queue?",
      "Explain linked list operations.",
      "How do you detect a loop in a linked list?",
      "What’s a binary tree and its traversal types?",
      "Explain heaps and their applications.",
      "What are graphs and how are they represented?",
      "What’s the use of priority queues?",
      "Explain union-find algorithm.",
      "How do you find duplicates in an array?",
      "Explain Kadane’s algorithm.",
      "How do you reverse a string or array?",
      "What’s the two-pointer technique?",
      "Explain sliding window algorithm.",
      "How do you find the kth largest element?",
      "Explain merge sort vs quick sort.",
      "What’s memoization?",
      "Explain trie data structure.",
      "How do you detect cycles in a graph?",
      "What’s topological sorting?",
      "Explain backtracking with examples.",
      "What’s difference between greedy and DP?",
      "Explain binary search tree operations.",
      "How do you balance an AVL tree?"
    ]
  },

  /* -------------------------------------------------------------------------- */
  /* 👩‍💻 Specialized Role Interviews (30 each)                                */
  /* -------------------------------------------------------------------------- */
  specialized: {
    frontend: [
      "How do you optimize web performance for mobile devices?",
      "Explain the concept of responsive web design.",
      "What are your strategies for cross-browser compatibility?",
      "How do you ensure accessibility in web applications?",
      "Explain the difference between semantic and non-semantic HTML.",
      "What’s the difference between React, Vue, and Angular?",
      "Explain state management in React.",
      "How do you handle component re-renders efficiently?",
      "What are hooks in React?",
      "Explain controlled vs uncontrolled components.",
      "How does reconciliation work in React?",
      "Explain the concept of virtual DOM.",
      "What’s the difference between client-side and server-side rendering?",
      "How do you optimize bundle size?",
      "What is code splitting?",
      "Explain lazy loading in React.",
      "What are higher-order components?",
      "How do you secure a front-end application?",
      "Explain hydration in Next.js.",
      "What are CSS-in-JS libraries?",
      "How do you manage environment variables in frontend?",
      "Explain different ways to style React components.",
      "What are context providers?",
      "Explain prop drilling and how to avoid it.",
      "What are error boundaries in React?",
      "How do you handle API errors gracefully?",
      "Explain testing strategies for frontend apps.",
      "What’s your approach to UI/UX collaboration?",
      "How do you manage global themes?",
      "Explain front-end build optimization techniques."
    ],

    backend: [
      "How do you handle database transactions and ensure data consistency?",
      "Explain RESTful API design principles.",
      "What strategies do you use for API rate limiting?",
      "How do you implement authentication and authorization?",
      "Explain database indexing and its impact on performance.",
      "What are ACID properties?",
      "How do you prevent SQL injection?",
      "Explain ORM and its advantages.",
      "What’s the difference between horizontal and vertical scaling?",
      "How do you design microservices architecture?",
      "Explain caching mechanisms for APIs.",
      "What’s the difference between JWT and OAuth?",
      "How do you implement logging and monitoring?",
      "Explain middleware in backend frameworks.",
      "What are webhooks and when to use them?",
      "How do you secure backend APIs?",
      "What’s rate limiting and throttling?",
      "Explain load balancing.",
      "How do you manage async tasks?",
      "What’s difference between monolithic and distributed systems?",
      "Explain reverse proxy usage.",
      "How do you connect backend with cloud storage?",
      "What’s database connection pooling?",
      "Explain message queues like RabbitMQ.",
      "How do you structure API versioning?",
      "Explain GraphQL vs REST.",
      "How do you manage environment variables securely?",
      "What’s difference between 401 and 403?",
      "How do you implement file uploads securely?",
      "Explain health checks in backend services."
    ],

    devops: [
      "Explain the difference between containers and virtual machines.",
      "How would you set up a CI/CD pipeline?",
      "What is infrastructure as code and why is it important?",
      "How do you monitor and troubleshoot production systems?",
      "Explain blue-green deployment strategy.",
      "What’s the difference between Docker and Kubernetes?",
      "Explain rolling updates.",
      "How do you manage secrets securely?",
      "What is observability in DevOps?",
      "Explain serverless computing.",
      "What’s difference between Jenkins and GitHub Actions?",
      "How do you implement automated testing in pipelines?",
      "What’s canary deployment?",
      "Explain version control best practices.",
      "What’s IaC using Terraform?",
      "How do you handle log aggregation?",
      "Explain disaster recovery strategies.",
      "What is auto-scaling?",
      "How do you secure CI/CD pipelines?",
      "What’s difference between on-prem and cloud infra?",
      "Explain monitoring tools like Prometheus and Grafana.",
      "How do you use Docker Compose?",
      "What’s Helm used for in Kubernetes?",
      "Explain rollbacks in deployments.",
      "What’s load testing and how do you do it?",
      "How do you handle zero downtime deployment?",
      "Explain network policies in Kubernetes.",
      "What’s container orchestration?",
      "How do you track metrics for deployments?",
      "Explain CI/CD pipeline stages."
    ],

    mobile: [
      "What are the key differences between native and cross-platform development?",
      "How do you handle different screen sizes and densities?",
      "Explain mobile app architecture patterns like MVVM.",
      "How do you optimize mobile app performance?",
      "What considerations are important for mobile app security?",
      "Explain lifecycle of an Android activity.",
      "What’s difference between fragments and activities?",
      "How do you implement push notifications?",
      "Explain offline-first architecture.",
      "How do you handle data persistence?",
      "Explain the role of ViewModel in Android.",
      "How do you handle permissions in mobile apps?",
      "What’s difference between Swift and Kotlin?",
      "Explain how Flutter uses widgets.",
      "What’s difference between React Native and Flutter?",
      "How do you reduce APK or IPA size?",
      "Explain state management in mobile apps.",
      "How do you profile app performance?",
      "What’s difference between synchronous and async calls?",
      "Explain REST API integration in mobile.",
      "How do you manage memory leaks?",
      "What’s use of Gradle in Android?",
      "Explain gesture handling.",
      "How do you test mobile apps?",
      "Explain dependency injection in mobile dev.",
      "What’s continuous integration for mobile?",
      "How do you ensure accessibility in apps?",
      "Explain animations and transitions in UI.",
      "What’s role of Firebase in mobile dev?",
      "How do you publish apps securely?"
    ]
  }
};
